language: python
python:   '3.6'
cache:    pip

# do not bother anyone 
notifications:
  email: false

# use docker
services:
  - docker

# pull image
before_install:
  - docker pull automatest/all

# install the project
install:
  - pip install -r requirements.txt
  - pip install --upgrade pytest pytest-pep8 pytest-cov coveralls

# run the tests
script:
  # TODO maybe use a specific order when testing
  - pytest --cov=src tests

# if (and when) we succeed coveralls will be published
after_success:
  - coveralls
