language: python
python:   '3.6'
cache:    pip

# do not bother anyone 
notifications:
  email: false

# install the project
install:
  - pip install -r requirements.txt
  - pip install --upgrade pytest pytest-pep8 pytest-cov coveralls

# run the tests
script:
  - pytest -m no_docker --cov=src tests/actions/test_processRequestGenerateInput.py
  - pytest -m no_docker --cov=src tests/actions/test_processRequestGenerateOutput.py
  - pytest -m no_docker --cov=src tests/actions/test_processRequestSolve.py

# if (and when) we succeed coveralls will be published
after_success:
  - coveralls
