language: python
python:   '3.6'
cache:    pip

# do not bother anyone 
notifications:
  email: false

# use docker
services:
  - docker

before_install:
  - docker pull automatest/all

# install the project
install:
  - pip install -r requirements.txt
  - pip install --upgrade pytest pytest-pep8 pytest-cov coveralls

# run the tests
script:
  - pytest --cov=src tests
  # - pytest --cov=src tests/actions/test_processRequestGenerateInput.py
  # - pytest --cov=src tests/actions/test_processRequestGenerateOutput.py
  # - pytest --cov=src tests/actions/test_processRequestSolve.py

# if (and when) we succeed coveralls will be published
after_success:
  - coveralls
